# Site settings
title: Die wunderbare Welt der Giraffen
description: Informative Website über Giraffen, ihre Unterarten, Lebensweise und Schutz
baseurl: "/WE_superstatic"
url: ""

# Build settings
markdown: kramdown
keep_files: [".git", ".svn", "CNAME"]