name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

# Erlaubt dem Action-Token, eure gh-pages-Branch zu beschreiben
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Repository klonen – mit voller History (fetch-depth: 0)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Ruby-Umgebung einrichten
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      # 3) Jekyll-Site bauen
      - name: Build with Jekyll
        run: |
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      # 4) Pages deployen
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          force_orphan: true
